[build]
command = "rm -rf dist && npm ci --legacy-peer-deps && npm run build && ls -la dist/"
publish = "dist/alojapp"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
NODE_VERSION = "18"
